footprint: [[-1.5,-1.5],[-1.5,1.5],[1.5,1.5],[1.5,-1.5]] #[[-1.0,-1.0],[-1.0,1.0],[1.0,1.0],[1.0,-1.0]]
footprint_padding: 0.01

robot_base_frame: small_hauler_1_base_footprint
update_frequency: 4.0
publish_frequency: 4.0
transform_tolerance: 0.5

resolution: 0.05 #0.2

obstacle_range: 15 #10.5
raytrace_range: 12.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: PointCloud2, clearing: true, marking: true, topic: /hauler_1/inference/point_cloud_filtered
, max_obstacle_height: 1.5, min_obstacle_height: 0.01, obstacle_range: 15.0, raytrace_range: 12.0}
#     laser: {data_type: PointCloud2, clearing: true, marking: true, topic: /hauler_1/inference/point_cloud_filtered
# , max_obstacle_height: 12.5, min_obstacle_height: 0.01, obstacle_range: 15.0, raytrace_range: 12.0}
# obstacles_scan:
#     observation_sources: scan
#     scan: {sensor_frame: hauler_1/hokuyo_link, data_type: LaserScan, topic: /hauler_1/laser/scan, marking: true, clearing: true}

inflation:
    inflation_radius: 1.75 #2.0
    cost_scaling_factor: 1.25 #1.08

inflation1:
    inflation_radius: 2.0
    cost_scaling_factor: 1.0
