controller_frequency: 10.0
recovery_behaviour_enabled: true
planner_frequency: 0.3

NavfnROS:
  allow_unknown: false #Default = true Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.


GlobalPlanner_SRC:
  allow_unknown: false # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.4 # A tolerance on the goal point for the planner.
  use_quadratic: true
  visualizepotential: true
  cost_factor: 0.6


DWAPlannerROS_SRC:
  # Robot configuration parameters
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_th: 3.2

  max_vel_x: 1.4
  min_vel_x: -0.1

  max_vel_y: 0.0001
  min_vel_y: -0.0001

  max_vel_trans: 1.5
  min_vel_trans: 0.2001

  max_vel_theta: 1.0
  min_vel_theta: 0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
  sim_time: 3.0
  sim_granularity: 0.02
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 25
  penalize_negative_x: true
  holonomic_robot: false

  # # Trajectory scoring parameters
  path_distance_bias: 12.0 # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 10.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 0.51 # The weighting for how much the controller should attempt to avoid obstacles
  forward_point_distance: 0.625 #0.325 The distance from the center point of the robot to place an additional scoring point, in meters
  stop_time_buffer: 0.3  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

  publish_cost_grid: true
  # # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
